steps:

- task: mabl-azure-devops-extension@1
  inputs:
    apiKey: 'votnLAZ5YaPWjqZYaUixIw'
    applicationId: 'https://durabledigital.com/'
    environmentId: 'https://durabledigital.com/'
    labels: 'Email sub test'

